---
title: "Sesion_2"
author: "Mynor_Petzera"
date: "2023-05-13"
output: html_document
---
Matrices

Función matrix(numeric, character of logical)
Representación gráficade las estructuras de datos
que se manejan en R.
byrow si es falso llena matriz en columnas
byrow si es verdadero llena matriz por filas

```{r}
matrix(1:9, byrow = TRUE, nrow = 3)
```
```{r}
matrix(1:9, nrow = 3)
```
```{r}
new_hope <- c(460.99, 314.4)
empire_strikes <- c(290.47, 247.9)
return_jedi <- c(309.3, 165.8)

box_office <- c(new_hope, empire_strikes, return_jedi)

star_wars_matrix <- matrix(box_office, byrow = TRUE, nrow = 3)

region <- c("US", "non-US")
titles <- c("A new hope", "The empire strikes back", "Return of jedi")

colnames(star_wars_matrix) <- region
rownames(star_wars_matrix) <- titles
star_wars_matrix

```
```{r}
star_wars_matrix

worldwide_vector <- rowSums(star_wars_matrix)

all_wars_matrix <- cbind(star_wars_matrix, worldwide_vector)

```
colSums & rbind

```{r}
total_cols <- colSums(all_wars_matrix)
totals_matrix <- rbind(all_wars_matrix, total_cols)

region <- c("US", "non-US", "Total")
titles <- c("A new hope", "The empire strikes back", "Return of jedi")

colnames(totals_matrix) <- region
rownames(totals_matrix) <- titles

totals_matrix
totals_matrix[2,1]
totals_matrix[2,]
totals_matrix[2,c(1,2,3)]
```

20/05/2023

Factors

```{r}
survey_vector <- c("M","F","F","M","M")
factor_survey_vector <- factor(survey_vector, order = TRUE, levels=c("M","F"))
levels(factor_survey_vector)<-c("Male","Female")
factor_survey_vector

male<-factor_survey_vector[1]
female<-factor_survey_vector[2]
male > female

```

SUMARIZACIÓN DE FACTOR

```{r}
summary(factor_survey_vector)
```

DATA FRAMES

data.frame()

```{r}
mtcars
```
```{r}
head(mtcars)
```
```{r}
str(mtcars)
```
```{r}
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

planets_df <- data.frame(name, type, diameter, rotation, rings)
```
```{r}
str(planets_df)
```
```{r}
planets_df[1,3:5]
planets_df[1:5,3:5]
planets_df[,3:5]
planets_df[1:4, "diameter"]
planets_df[1:4,c("diameter","rotation")]
rings_vector<-planets_df$rings

subset(planets_df, subset = diameter < 1)
subset(planets_df, subset = rings == TRUE)
subset(planets_df, subset = rings == 1)
subset(planets_df, subset = rings == 0)
```

SORTING

order()

```{r}
planets_df
order(planets_df$diameter)

```

