---
title: "Homework_4"
author: "Mynor_Petzera"
date: "2023-06-27"
output: html_document
---

```{r}
library(dplyr)
library(readr)
library(ggplot2)

ruta <- "diamonds.csv"
diamonds <- read.csv(ruta)
str(diamonds)

```

DISPERSION

```{r}
  ggplot(diamonds, aes(x = carat, y = price, color = clarity)) +
  geom_point()+
  expand_limits(y=0)
  
```

HISTOGRAMA

```{r}
ggplot(diamonds, aes(x=price)) +
  geom_histogram(bins=40)
```
```{r}
ggplot(diamonds, aes(x=price)) +
  geom_histogram(bins=40)+
  scale_x_log10()
```
BOXPLOTS

```{r}
ggplot(diamonds, aes(x = cut, y = price)) +
  geom_boxplot() +
  scale_y_log10()
```

```{r}
ggplot(diamonds, aes(x = cut, y = price, fill = cut)) +
  geom_boxplot() +
  scale_y_log10()
```
FACETING

```{r}
filtered_price <- diamonds %>%
  filter(price > 1000 & cut %in% c("Good", "Ideal", "Premium"))

ggplot(filtered_price, aes(x = cut, y = depth)) +
  geom_col()
```

```{r}
filtered_price <- diamonds %>%
  filter(price > 1000 & cut %in% c("Good", "Ideal", "Premium"))

ggplot(filtered_price, aes(x = cut, y = depth)) +
  geom_col()+
  facet_wrap(~ clarity, nrow = 1)
```
```{r}
filtered_price <- diamonds %>%
  filter(price > 1000 & cut %in% c("Good", "Ideal", "Premium"))

ggplot(filtered_price, aes(x = cut, y = depth, fill = clarity)) +
  geom_col()+
  facet_wrap(~ clarity, nrow = 1)
```

GROUPING AND SUMMARIZING

```{r}
median_dimension_diamond <- diamonds %>%
  group_by(cut) %>%
  summarise( mediaX = median(x), mediaY = median(y), mediaZ = median(z))

median_dimension_diamond
```
```{r}
cut_premium <- diamonds %>%
  filter(cut == "Premium") %>%
  group_by(clarity) %>%
  summarise(minPrice = min(price), maxPrice = max(price))

cut_premium
```
```{r}
ggplot(cut_premium, aes(x = clarity, y = maxPrice, fill = clarity))+
  geom_col()
```

